add possibility to override default html templates
fydrah/loginapp pull request #46
Opened 2021-05-06 14:58 UTC by Imunhatep

Something similar to that might close #45

2021-05-09 19:56 UTC, justusbunsi commented
After playing around to get this partial override implemented, I don't see any advantage in it anymore. 😀
At the moment there are only two template files so I guess, it's fine to override both files at once.

2021-05-13 15:10 UTC, fydrah commented
Hi @Imunhatep ,

Thanks for this PR.

I tested the override, and I don't this this work as expected. If we want to fill a multi-line html template, this will not work. We must change configmap template with something like:

```
[...]
  error.html: |
    {{ .Values.templates.error | nindent 4 }}
[...]
```
Same for the example:
```
# Configuration overrides html templates content used by loginapp to display error and token pages
# Example:
#
#  templates:
#    token: |
#      <html> ....
templates:
```

Also, as @justusbunsi suggested, a partial override should be allowed. Maybe users will only want to override error or token template (mainly only the token template). It's only a few "if" conditions to add, and change "and" operators by "or". This is a few updates for a lot of more conveniences

2021-05-13 15:16 UTC, fydrah requested changes

2021-05-13 15:16 UTC, fydrah commented on helm/loginapp/templates/configmap.yaml
> +{{- if and .Values.templates.error .Values.templates.token}}
`or`

2021-05-13 15:16 UTC, fydrah commented on helm/loginapp/templates/configmap.yaml
> +data:
* conditional include, or a loop over all `templates` keys
* should support multi-line (`|-` & `| nindent 4`)

2021-05-13 15:16 UTC, fydrah commented on helm/loginapp/templates/deployment.yaml
> +            {{- if and .Values.templates.error .Values.templates.token }}
`or`

2021-05-13 15:16 UTC, fydrah commented on helm/loginapp/templates/deployment.yaml
> +      {{- if and .Values.templates.error .Values.templates.token }}
`or`

2021-05-13 15:16 UTC, fydrah commented on helm/loginapp/templates/deployment.yaml
> +          items:
* conditional include, or a loop over all `templates` keys
* should support multi-line (`|-` & `| nindent 4`)

2021-05-13 15:16 UTC, fydrah commented on helm/loginapp/values.yaml
> +#    token: {{`<html><body><title>Hello token</title></body></html>`}}
update example with multi-line

2021-05-17 15:32 UTC, Imunhatep commented
Personally I do not consider " a partial override " as a must have. 
Would prefer to leave this part for a separate PR to the ones who would ask/suggest it.

2021-05-18 15:15 UTC, fydrah commented
Thanks @Imunhatep  for the update, I tested the new version and it works pretty well with the loop over templates names :)

You're right it's not a must have, but it's an improvement!

Also thanks for the dex dependency update, it has been updated last time (by mistake..) to this old repository, and not the  official one..

2021-05-18 15:16 UTC, merged